// MODIFICA ESTA URL POR LA DEL SERVICIO WEB DESPUES DE HABERLO DESPLEGADO
const AS_URL_BASE = "https://script.google.com/a/~/macros/s/AKfycbyuQ0K960PWtE5spVStE9StkEL9a83fGqj2UYQn0nSwOz0OaZd0ZMWP9W8PL7NYHYNB/exec";
