// MODIFICA ESTA URL POR LA DEL SERVICIO WEB DESPUES DE HABERLO DESPLEGADO
const AS_URL_BASE = "https://script.google.com/macros/s/AKfycbz2J7NoL4gXuKC7AHVCMR3RQ586_ZLyiEY5e--ywwjBkp5tygafuZklEKcLp27QznML/exec";
